<?php
///////////////////////////////////////////////// Sidebar Widgets
if ( function_exists('register_sidebar') )
register_sidebar(array('name'=>'Home I',
	 'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Home II',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Home III',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h2 class="title" id="last"><span>',
	'after_title' => '</span></h2>',
));
register_sidebar(array('name'=>'Home IV',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Home V',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Blog I',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Blog II',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Blog III',
	 'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Blog IV',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Blog V',
'description' => __( 'Use this widget area for the sidebar, which can be selected in the layout theme options area - Right Sidebar.' ),
	'before_widget' => '',
	'after_widget' => '',
'before_title' => '<h2 class="title">',
	'after_title' => '</h2>',
));
register_sidebar(array('name'=>'Footer I',
'description' => __( 'Use this widget area for footer widgets only.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h1 class="title">',
	'after_title' => '</h1>',
));
register_sidebar(array('name'=>'Footer II',
'description' => __( 'Use this widget area for footer widgets only.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h1 class="title">',
	'after_title' => '</h1>',
));
register_sidebar(array('name'=>'Footer III',
'description' => __( 'Use this widget area for footer widgets only.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h1 class="title">',
	'after_title' => '</h1>',
));
register_sidebar(array('name'=>'Footer IV',
'description' => __( 'Use this widget area for footer widgets only.' ),
	'before_widget' => '',
	'after_widget' => '',
	'before_title' => '<h1 class="title">',
	'after_title' => '</h1>',
));
?>